version: '3'

services:
  web:
    image: mhy5413/clipmk-docker:latest
    container_name: web
    restart: unless-stopped
    expose:
      - 8080
    ports:
      - 8080:8080
  nginx:
    image: mhy5413/clipmk-nginx:latest
    restart: unless-stopped
    volumes:
      - ./conf/:/etc/nginx/conf.d
      - /data/certbot/conf:/etc/letsencrypt
      - /data/certbot/www:/var/www/certbots
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
#  redis:
#    image: redis:alpine
#    container_name: redis_boot
#    command: redis-server --port 6379
#    hostname: redis_boot
#    labels:
#      - "name=redis"
#      - "mode=standalone"
#    ports:
#      - 6379:6379
  admin:
    image: mhy5413/clipmk-admin
    container_name: admin
    restart: unless-stopped
    expose:
      - 8000
    ports:
      - 8000:8000
    