server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver

#    url: jdbc:mariadb://127.0.0.1:3306/homepage?&serverTimezone=UTC&autoReconnect=true&allowMultiQueries=true&characterEncoding=UTF-8
#    username: root   
#    password: 2142
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: mhy5413@gmail.com
    password: audgks4338
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    show_sql: true
    properties:
      hibernate:
        format_sql: true         

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace 
      SQL: DEBUG      

application:
  security:
    jwt:
      secret-key: 6D5A7134743777217A25432A462D4A404E635266556A586E3272357538782F41
      access-token:  
        expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
  post:
    best-post:
      viewCnt: 3